# Question 1

In [20]:
import numpy as np
import matplotlib.pyplot as plt

def model(y,t):
    dydt = -2 * y * t
    return dydt
y0=1
t=np.linspace(0,2,100)
y=odeint(model,y0,1)

plt.plot(y,t)
plt.xlabel('Y time')
plt.ylabel('y(t)')
plt.title ('Solution of dy/dt = -2yt with y(0)=1')
plt.show()


NameError: name 'odeint' is not defined

# Question 2

In [7]:
import scipy as sc
import numpy as np

A = np.array([[2,4,6],[5,3,2],[7,8,9]])
print (A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [9]:
B = np.array([[18],[13],[30]])
print (B)

[[18]
 [13]
 [30]]


In [12]:
C = sc.linalg.inv(A).dot(B)
print (C)

[[ 4.5]
 [-7.5]
 [ 6.5]]


In [14]:
solution = sc.linalg.solve(A,B)
print (solution)

[[ 4.5]
 [-7.5]
 [ 6.5]]


# Question 3

In [ ]:
import numpy as np
import matplotlib.pyploy as plt


range (1,16)


links = (https://api.open-meteo.com/v1/forecast?latitude=2.5&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1)


plt.plot(x,y)
plt.xlabe('Hourly Time')
plt.ylabel('Temperature')
plt.title('The number of days for the forecast')
plt.show()

